### ISSUE TITLE
Always start from empty initial state

### ISSUE THREAD

**Issue by mrsmkl** [TrueBitFoundation/ocaml-offchain#19]
Instead of having initialized memory and tables, just have some instructions that will initialize the state.

**Comment by terminaldweller** [comment]
sami what do you mean by an "instruction" that will initialize the state?
also could you please explain why we would want to initialize the VM from a non-empty state? I'm not sure if i understand the question.

**Comment by mrsmkl** [comment]
Well in wasm modules there are stuff for initializing memory, globals, and anyfunc table. Currently the interpreter handles these segments to create the initial state. Instead of doing that, we could have empty initial state and have a program that sets the memory etc.

**Comment by mrsmkl** [comment]
Done in #61
