### ISSUE TITLE
Compiler tool-chain

### ISSUE THREAD

**Issue by mrsmkl** [TrueBitFoundation/ocaml-offchain#6]
Find out how to compile something from C or Rust to webasm, and then test if it works with the interpreter.

**Comment by terminaldweller** [comment]
besides the binaryen/emscripten combo there is also wasmfiddle(https://github.com/wasdk/WasmFiddle/issues/4) for C/Cpp.

**Comment by mrsmkl** [comment]
Here are simple instructions:
https://github.com/TrueBitFoundation/ocaml-offchain/wiki/Running-C-programs

Now working on more complex programs.
