### ISSUE TITLE
Repo License

### ISSUE THREAD

**Issue by terminaldweller** [TrueBitFoundation/ocaml-offchain#7]
We need to license the repo properly.
The original repo's license for the interpreter and test folder are Apache V 2.0. i guess it should be fine to relicense it to MIT since its Apache. any thoughts?

**Comment by teutsch** [comment]
Let's switch it to MIT!

**Comment by terminaldweller** [comment]
we would have to clean-up the repo, get rid of the w3c docs and papers, since those have different licences and we don't need them anyways and then apply our license to the new code.

**Comment by teutsch** [comment]
This sounds like a good plan.  Can you do the cleanup?

**Comment by terminaldweller** [comment]
sure, will do.

**Comment by mrsmkl** [comment]
Fixed in #16
