### ISSUE TITLE
Make this a RPC Server

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/ocaml-offchain#98]
Had the idea of turning this into a JSON RPC Server like Parity or Geth.
Then we write software that can act as a client.

Benefits:
Easier installation for other projects that depend on this (webasm-solidity, coindrop, etc)
Allow us to write client in any language(s) we want
Easier to document the API

**Comment by mrsmkl** [comment]
Perhaps there could be like a JS server that would call the executable.
